# Generated by Django 2.2.7 on 2019-12-14 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarybasic',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='salarybasicplus',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='laborcontract',
            name='dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comp.Department'),
        ),
        migrations.AlterField(
            model_name='laborcontract',
            name='subdept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comp.SubDepartment'),
        ),
        migrations.AlterField(
            model_name='laborcontract',
            name='term',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='salaryscale',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
