# Generated by Django 2.2.7 on 2019-11-07 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('company_name', models.TextField()),
                ('company_short_name', models.TextField(null=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.TextField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('subdept_id', models.AutoField(primary_key=True, serialize=False)),
                ('subdept_name', models.TextField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SubdeptOfDept',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startday', models.DateTimeField()),
                ('endday', models.DateTimeField()),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comp.Department')),
                ('subdept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comp.SubDepartment')),
            ],
        ),
        migrations.CreateModel(
            name='DeptOfCompany',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startday', models.DateTimeField()),
                ('endday', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comp.Company')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comp.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_code', models.CharField(max_length=20)),
                ('code_tax', models.CharField(max_length=20)),
                ('cert_day', models.DateTimeField()),
                ('cert_place', models.TextField()),
                ('company_phone', models.CharField(max_length=20)),
                ('company_fax', models.CharField(max_length=20)),
                ('company_address', models.TextField()),
                ('company_email', models.CharField(max_length=50)),
                ('startday', models.DateTimeField()),
                ('endday', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comp.Company')),
            ],
        ),
    ]
